# Generated by Django 2.2.5 on 2019-09-16 10:24

import bbq_organizer.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[bbq_organizer.validators.validate_date])),
                ('slug', models.SlugField(blank=True, max_length=8, unique=True)),
                ('author', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('extras', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete='CASCADE', to='bbq_organizer.Event')),
            ],
        ),
        migrations.CreateModel(
            name='MeatOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete='CASCADE', to='bbq_organizer.Event')),
                ('meat', models.ForeignKey(on_delete='CASCADE', to='bbq_organizer.MeatType')),
            ],
        ),
        migrations.CreateModel(
            name='MeatChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat', models.ForeignKey(on_delete='CASCADE', to='bbq_organizer.MeatType')),
                ('signup', models.ForeignKey(on_delete='CASCADE', to='bbq_organizer.SignUp')),
            ],
        ),
    ]
