version: '3'

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      context: ..
      dockerfile: ./compose/dev/django/Dockerfile
    image: bbq_organizer_dev_django
    container_name: bbq_organizer_dev_django
    depends_on:
      - postgres
    volumes:
      - ..:/opt/app
    env_file:
      - ../.envs/.dev/.django
      - ../.envs/.dev/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: ..
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bbq_production_postgres
    container_name: bbq_organizer_dev_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.envs/.dev/.postgres
