version: '3'

volumes:
  production_postgres_data: {}

services:
  django:
    build:
      context: ..
      dockerfile: ./compose/production/django/Dockerfile
    image: bbq_organizer_production_django
    depends_on:
      - postgres
    env_file:
      - ../.envs/.production/.django
      - ../.envs/.production/.postgres
    ports:
      - "8123:5000"
    command: /start

  postgres:
    build:
      context: ..
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bbq_organizer_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.envs/.production/.postgres
